---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
  - name: ubuntu-13.04-teamcity

provisioner:
  solo_rb:
    file_cache_path: /var/chef/cache/

suites:
  - name: default
    run_list: 
      - recipe[teamcity]
      - recipe[teamcity::monit]
      - recipe[minitest-handler]
    attributes: {
      postgresql: {
        password: {
          postgres: 'pass123',
          teamcity: 'pass456'
        }
      }
    }
