---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
  - name: ubuntu-13.04

suites:
  - name: default
    run_list: 
      - recipe[teamcity-test::fast_integration]
      - recipe[minitest-handler]
    attributes: {
      postgresql: {
        password: {
          postgres: 'pass123',
          teamcity: 'pass456'
        }
      }
    }
